### ISSUE TITLE
paella_sampling.ipynb Gdown downloads dont work

### ISSUE THREAD

**Issue by misza222** [dome272/Paella#12]
Getting an error when trying to download models using `gdown`
![image](https://user-images.githubusercontent.com/89839/203815862-9d8ebfd4-76b6-40d8-adff-51b2ad319bd1.png)

**Comment by backnotprop** [comment]
`curl -L -s -o ./model_600000.pt 'https://drive.google.com/uc?id=1ACIb2nrZk_jQID8bP9qYKkNZVldM94zw&confirm=t`

and

`curl -L -s -o ./model_50000_img.pt 'https://drive.google.com/uc?id=1VVWPXFLdI18TXhqlYmfMNT41Suz9pJr8&confirm=t`
