### ISSUE TITLE
Add Paellaaa to community section

### ISSUE THREAD

**Issue by AmericanPresidentJimmyCarter** [dome272/Paella#14]
Hello friends, hlky and I have been working on a fork of Paella with some alterations. These are: dual CLIP and T5 embeddings and cross attention. Feel free to link to our repository in your community "ongoing research" section.

We are scaling up training and hope to release weights and a demo once completed. Thanks!

[Paellaaa](https://github.com/AmericanPresidentJimmyCarter/Paellaaa)

**Comment by dome272** [comment]
Added. Can you add a link to track your training to wandb to your repo?

**Comment by AmericanPresidentJimmyCarter** [comment]
Thanks, currently training is down due to the migration and I'm unsure hlky wants to publish them since they have system details and CLI output. I might publish the data from them after the fact. We are still tuning the fork too as there are some issues with loss spike that might require additional layernorm or other steps.
