### ISSUE TITLE
Image variation finetuned model

### ISSUE THREAD

**Issue by ArielReplicate** [dome272/Paella#17]
Hi
The colab script syas there's a fintuned model needed for runing image variation. Can you upload it?

I'm trying this way
```
input_image = Image.open(str(input_image))
num_outputs = int(num_outputs)
latent_shape = (32, 32)
with torch.inference_mode():
    with torch.autocast(device_type="cuda"):
        input_image = clip_preprocess(input_image).to(device).unsqueeze(0)
        clip_embeddings = clip_model.encode_image(input_image).float()
        clip_embeddings = torch.repeat_interleave(clip_embeddings, num_outputs, dim=0)
        sampled = sample(model, clip_embeddings, T=12, size=latent_shape, starting_t=0, temp_range=[1.0, 1.0],
                                 typical_filtering=True, typical_mass=0.2, typical_min_tokens=1,
                                 classifier_free_scale=5, renoise_steps=11)
sampled = decode(sampled[-1])
```
and getting very bad results.
Like these ones (Input on left and 3 outputs on the right)

![Screenshot from 2022-12-09 18-09-51](https://user-images.githubusercontent.com/116253211/206744160-4b75498b-05d8-4c17-8c4b-992362e6d6b7.png)

**Comment by maubreville** [comment]
Hey there, 

as visible in the 4th cell of the colab notebook, you can download the model that was finetuned with 50.000 steps with:

`!curl -L -s -o ./model_50000_img.pt 'https://drive.google.com/uc?id=1VVWPXFLdI18TXhqlYmfMNT41Suz9pJr8&confirm=t'  # Finetuned Image-Model
`

Best regards,

Marc

**Comment by ArielReplicate** [comment]
Oh sorry I missed that. 
Thank you for the fast reply.
