### ISSUE TITLE
Is this a bug or I missed something?

### ISSUE THREAD

**Issue by 531619091** [dome272/Paella#28]
Hi, when I check the vqgan.py file, In the line of 110, self.encode(x, quantize), it has a quantize parameter, but in the encode function definition (line of 91), it has no this parameter . thanks.

**Comment by pabloppp** [comment]
This is a typo, yes. Line 110 shouldn't have any extra parameter, since in Paella we always work with quantized latents, we never had the need to disable the quantization. This has most likely slipped from some of our LDM experiments.

**Comment by 531619091** [comment]
> This is a typo, yes. Line 110 shouldn't have any extra parameter, since in Paella we always work with quantized latents, we never had the need to disable the quantization. This has most likely slipped from some of our LDM experiments.

Got it! Thanks for your reply.
