### ISSUE TITLE
How much ram is needed on cpu?

### ISSUE THREAD

**Issue by ClashSAN** [dome272/Paella#7]
I'm trying to run the paella_sampling.ipynb locally with 8gb normal ram, but it appears in the 5th block it fills my 16gb swap and my ram.

I run this on a linux laptop through a venv. Is the code for the notebook not optimized/outdated ?

venv commandline: steps

1. source myvenv/bin/activate
2. pip install ipykernel
3. python -m ipykernel install --user --name=myvenv
4. pip install Jupyter
5. jupyter notebook
6. (open and run paella_sampling.ipynb through launched web browser)

I would very much like to test this project for local install and use on cpu, but I don't know how to use the other files provided.

**Comment by oxysoft** [comment]
A more comprehensive explanation of the VRAM requirements for Paella in general would be nice. The base UNet seems to take over 5.5GB of VRAM, which I find strange since I can run Stable Diffusion smoothly on this 6GB card.

**Comment by ClashSAN** [comment]
Ok, successful. 2500x443
![image](https://user-images.githubusercontent.com/98228077/202929670-dd674313-5fff-49aa-9fef-131f8470333e.png)
This generation took around 4 minutes. I used the 2gb sized pt file.

It turned out my swap was not being freed. Some kind of issue that is solvable with a restart.. I had to shut it down the first time because it was going to approach the 16gb swap limit. It does us lots of ram when loading the model in codeblock 5.

My answer to my question would you probably need 16gb total, I don't know if when using a gpu under 24gb it uses regular ram to accomodate
